bts-retitle: fix missing bug error handling.
Before:

    $ bts-retitle 42
    Traceback (most recent call last):
      File ".../bts-retitle", line 42, in <module>
        main()
      File ".../bts-retitle", line 24, in main
        [bug] = debianbts.get_status(opts.no)
        ^^^^^
    ValueError: not enough values to unpack (expected 1, got 0)

After:

    $ bts-retitle 42
    bts-retitle: bug #42 not found